FROM golang:1.12-alpine

RUN apk update && apk upgrade && apk add --no-cache bash git openssh gcc musl-dev

WORKDIR /app

COPY ./ /app

RUN go mod download

RUN go get github.com/juragankoding/golang_graphql_training

ENTRYPOINT CompileDeamon --build="go build server.go" --command:./server