// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/juragankoding/golang_graphql_training/domain"
	"github.com/juragankoding/golang_graphql_training/models"
)

type ResultInsert interface {
	IsResultInsert()
}

type ResultInsertCategories struct {
	Status string             `json:"status"`
	Code   int                `json:"code"`
	Data   *domain.Categories `json:"data"`
}

func (ResultInsertCategories) IsResultInsert() {}

type ResultGetAllJenisBarang struct {
	Status string                `json:"status"`
	Code   int                   `json:"code"`
	Data   []*models.JenisBarang `json:"data"`
}

func (ResultGetAllJenisBarang) IsResultInsert() {}

type ResultJenisBarang struct {
	Status string              `json:"status"`
	Code   int                 `json:"code"`
	Data   *models.JenisBarang `json:"data"`
}

func (ResultJenisBarang) IsResultInsert() {}
