// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/juragankoding/golang_graphql_training/models"
)

type ResultInsert interface {
	IsResultInsert()
}

type Karyawan struct {
	ID         int    `json:"id"`
	IDKaryawan string `json:"idKaryawan"`
	Nama       string `json:"nama"`
	Email      string `json:"email"`
	NoHp       string `json:"noHp"`
}

type ResultInsertBarang struct {
	Status string         `json:"status"`
	Code   int            `json:"code"`
	Data   *models.Barang `json:"data"`
}

func (ResultInsertBarang) IsResultInsert() {}

type ResultGetAllJenisBarang struct {
	Status string                `json:"status"`
	Code   int                   `json:"code"`
	Data   []*models.JenisBarang `json:"data"`
}

func (ResultGetAllJenisBarang) IsResultInsert() {}

type ResultJenisBarang struct {
	Status string              `json:"status"`
	Code   int                 `json:"code"`
	Data   *models.JenisBarang `json:"data"`
}

func (ResultJenisBarang) IsResultInsert() {}
