// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ResultInsert interface {
	IsResultInsert()
}

type ResultJenisBarang struct {
	Status string `json:"status"`
	Code   int    `json:"code"`
}

func (ResultJenisBarang) IsResultInsert() {}
